Allow to get the body as String
cdimascio/swagger-spring-functional pull request #28
Opened 2021-04-11 22:53 UTC by magro

We need to calculate a signature of the body (String), which is not possible today because on successful validation the body is deserialized with jackson. Consuming the body additionally is not straight forward, therefore it makes sense that the validator allows to handle the consumed body as String.

To support this case, it's now possible to specify
* `String` as body type and
* an identity function for transforming the read body value

This solution gives some flexibility on how to transform the String
to the desired value passed to the handler - there may be other cases
than just getting the String.

An alternative solution to support this case would be to handle the
get-string-body case very specifically, but then for other cases
other solutions might have to be introduced. Therefore the more
flexible solution is preferred.

2021-04-13 20:12 UTC, magro commented
Hi @cdimascio, any chance to get that reviewed/merged/released soonish?

2021-04-19 20:59 UTC, magro commented
ping @cdimascio

2021-04-22 01:56 UTC, cdimascio commented
@magro apologies. somehow i missed this. reviewing

2021-04-22 02:00 UTC, cdimascio requested changes
@magro please update the README to include this new functionality

2021-05-10 19:07 UTC, magro commented
@cdimascio Ha, now it took me some time :-) I updated the README now...

Update: while going through the README I also noticed that java support is needed ;-) Therefore I removed the default argument and added a separate/overloading method instead...

2021-05-21 07:58 UTC, magro commented
Ping @cdimascio again :-)

2021-05-22 15:08 UTC, merged

2021-05-22 15:26 UTC, cdimascio commented
@magro apologies for the delay. bintray discontinued there service on may 1. i had use them to manage publication to mavencentral and center. i need to find a new method.

in the meantime, i published a new package using github's package manager. for now, you can pull the latest from there

https://github.com/cdimascio/openapi-spring-webflux-validator/packages/806006

2021-05-22 18:08 UTC, magro commented
Thanks for merging and publishing via github! 

You can publish to maven central via sonatype, once the setup is done it's quite easy. https://central.sonatype.org/publish/publish-guide/

2021-05-22 21:45 UTC, cdimascio commented
thanks a lot!
i just published to sonatype. the staging event has not yet started. this used to take up to a few hours when using bintray. the same may be the case here.

2021-05-24 01:06 UTC, cdimascio commented
it's successfully published to sonatype, i believe it should make it to mavencentral shortly

![image](https://user-images.githubusercontent.com/4706618/119283319-9d51a300-bc0a-11eb-8a97-d07e345a13e8.png)

2021-05-24 01:20 UTC, cdimascio commented
should be on mavencentral now

2021-06-23 11:24 UTC, magro commented
Awesome, thanks! :+1: